# Site settings
title: Your awesome title
motto: Your motto
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
<<<<<<< HEAD
=======

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: src
destination: public

assets:
  compress:
    css: sass
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: www.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"
    - "bundle.js.map"
    - "*.svg"
    - "*.eof"
    - "*.ttf"

  sources:
    - src/_assets/css
    - src/_assets/fonts
    - src/_assets/img
    - src/_assets/projects

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['node_modules', 'Gemfile', '.asset-cache', 'build-prod.sh', 'build-dev.sh']

gems:
  - jekyll-assets
  - jekyll_pages_api
  - jekyll-react

theme: jekyll-theme-minimal
>>>>>>> da0b1126e1cbecb2e712f513d7019c6ca766270b
